### ISSUE TITLE
zookeeper vs libkv

### ISSUE THREAD

**Issue by cinterloper** [magneticio/vamp-gateway-agent#1]
Hey, quick question,
have you considered abstracting to docker's libkv
https://github.com/docker/libkv/blob/master/store/zookeeper/zookeeper.go#L157

removing a direct dependence on zookeeper?

I liked the REST interface on vamp-router

**Comment by dragoslav** [comment]
Definitely we can use libkv and probably we will. Reason why we use right now only ZooKeeper is because Mesos/Marathon use it. We even thought to support also Consul and/or etcd in the first release (Vamp 0.8.0) but since we are not going to use it now we didn't want to spend additional time on testing different setups.
Main reasons why we don't use Vamp Router now is because agent allows us faster Vamp iterations, e.g. changing how we use HAProxy fe/be/filters, to avoid often updates of Router in production due to new Vamp features (Vamp will generate HAProxy configuration) etc.
So, this agent is very Vamp centric while Vamp Router is more complete and independent of Vamp. I guess that in the future we could start using Router again for Vamp (better than to start adding higher level features to the agent).

**Comment by dragoslav** [comment]
Implemented using `libkv` for `ZooKeeper`.
