### ISSUE TITLE
Redundant haproxy logging

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp-gateway-agent#23]
Just noticed this being printed on my console using the quick-start:

```
{
       "message" => "<134>Sep 28 21:24:33 haproxy[48]: {\"ci\":\"127.0.0.1\",\"cp\":51972,\"t\":\"28/Sep/2016:21:24:33.158\",\"ft\":\"a7ad6869e65e9c047f956cf7d1b4d01a89eef486\",\"b\":\"o_a7ad6869e65e9c047f956cf7d1b4d01a89eef486\",\"s\":\"15273989f22771b96c85d496176bdf19add88120\",\"Tq\":0,\"Tw\":0,\"Tc\":0,\"Tr\":12,\"Tt\":12,\"ST\":404,\"B\":127,\"CC\":\"-\",\"CS\":\"-\",\"tsc\":\"----\",\"ac\":5,\"fc\":1,\"bc\":0,\"sc\":1,\"rc\":0,\"sq\":0,\"bq\":0,\"hr\":\"\",\"hs\":\"\",\"r\":\"GET /bla HTTP/1.1\"}\n",
      "@version" => "1",
    "@timestamp" => "2016-09-28T21:24:33.158Z",
          "type" => "haproxy",
          "host" => "172.17.0.1",
       "metrics" => "{\"ci\":\"127.0.0.1\",\"cp\":51972,\"t\":\"28/Sep/2016:21:24:33.158\",\"ft\":\"a7ad6869e65e9c047f956cf7d1b4d01a89eef486\",\"b\":\"o_a7ad6869e65e9c047f956cf7d1b4d01a89eef486\",\"s\":\"15273989f22771b96c85d496176bdf19add88120\",\"Tq\":0,\"Tw\":0,\"Tc\":0,\"Tr\":12,\"Tt\":12,\"ST\":404,\"B\":127,\"CC\":\"-\",\"CS\":\"-\",\"tsc\":\"----\",\"ac\":5,\"fc\":1,\"bc\":0,\"sc\":1,\"rc\":0,\"sq\":0,\"bq\":0,\"hr\":\"\",\"hs\":\"\",\"r\":\"GET /bla HTTP/1.1\"}",
            "ci" => "127.0.0.1",
            "cp" => 51972,
             "t" => "28/Sep/2016:21:24:33.158",
            "ft" => "a7ad6869e65e9c047f956cf7d1b4d01a89eef486",
             "b" => "o_a7ad6869e65e9c047f956cf7d1b4d01a89eef486",
             "s" => "15273989f22771b96c85d496176bdf19add88120",
            "Tq" => 0,
            "Tw" => 0,
            "Tc" => 0,
            "Tr" => 12,
            "Tt" => 12,
            "ST" => 404,
             "B" => 127,
            "CC" => "-",
            "CS" => "-",
           "tsc" => "----",
            "ac" => 5,
            "fc" => 1,
            "bc" => 0,
            "sc" => 1,
            "rc" => 0,
            "sq" => 0,
            "bq" => 0,
            "hr" => "",
            "hs" => "",
             "r" => "GET /bla HTTP/1.1"
}
```

This shows information in a _message_ key, a _metrics_ key and on top of that all fields are individual _keys_. Why is this being stored _3_ (!) times?

**Comment by dragoslav** [comment]
By default Logstash is [configured](https://github.com/magneticio/vamp-docker/blob/master/clique-base/logstash/logstash.conf) to do this (including logging everything to stdout). You can configure in Vamp what should be the HAProxy log format (`message`). In order to easily debug this/your custom configuration, `metrics` is result where for instance log timestamp is removed (encoded JSON) and the next step is importing result to ES.
If you want to optimize (and you should) this configuration, a part of not storing `message` and `metrics`, mostly `Tt`, `ST` and `ft` are relevant (depends of course on your needs).
Another thing is that you should setup ES/Logstash etc. in certain production grade way, which we don't cover at all.
In the following weeks we plan to add more examples related to metrics collection, aggregation etc. maybe as an addition even using something else than ES.

**Comment by harmw** [comment]
Alright, so if I stop logging the `metrics` and `message` fields all is still good? The workflow-agent will still be able to pick up the right data?

**Comment by dragoslav** [comment]
Yes, it should be fine.

**Comment by iamtew** [comment]
This has been changed in 0.9.3 as we moved to filebeat for log shipping.

See commit 9c2ad11 and later.
